# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(data: {clerkId: "user_3JWkItfxp9lYhDVRpU72bRYOlSA", email: "melissavlqf@gmail.com", imageUrl: "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NJZzZXNTlEekJVSFdMNm45OGlJNm1WX3kzSVJRTXI4Q2llYzYydDZmNFNjM0ROUGh4Y2x3PXMxMDAwLWMiLCJzIjoiRkx6c256U2lsNW93azFnanlUd2RiSldYby9rdWJtWW8zYmtGaGxhZ081WSJ9", username: "melissaquintero"})
}